export default {
  showFooter: false,
  isSidebarCompact: false,
  showBreadcrumb: true,
  menuAutoCollapsed: true,
  mode: 'light',
  layout: 'side',
  splitMenu: false,
  sideMode: 'light',
  isFooterAside: false,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: true,
  showHeader: false,
  brandTheme: '#0052D9',
};
